version: '2'
services:
  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.1.1
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_REST_LISTENERS: http://localhost:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://localhost:8081
      KAFKA_REST_HOST_NAME: localhost
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.container.pull_image: always
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: '32181'
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.container.pull_image: always
  kafka:
    image: confluentinc/cp-kafka:3.1.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.container.pull_image: always
  schema-registry:
    image: confluentinc/cp-schema-registry:3.1.1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:32181
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.container.pull_image: always
